namespace BankManager.Models;

/// <summary>
///     Account owned by <paramref name="ownerId" />, <seealso cref="User" />. which defines the object
/// </summary>
/// <param name="id"></param>
/// <param name="name"></param>
/// <param name="balance"></param>
/// <param name="ownerId"></param>
/// <param name="createdAt"></param>
public class Account(
    int id,
    string name,
    decimal balance,
    int ownerId,
    DateTime createdAt
)
{
    /// <summary>
    ///     ID, auto-generated by DataBase, unique to each Account
    /// </summary>
    public int Id { get; init; } = id;

    /// <summary>
    ///     Name of the Account
    /// </summary>
    /// <example>The account can be named as "Savings", or "Family"</example>
    public string Name { get; init; } = name;

    /// <summary>
    ///     The balance of the Account
    /// </summary>
    public decimal Balance { get; set; } = balance;

    /// <summary>
    ///     the <see cref="User" /> ID who owns this Account
    /// </summary>
    public int OwnerId { get; init; } = ownerId;

    /// <summary>
    /// </summary>
    public DateTime CreatedAt { get; init; } = createdAt;
}